---
- name: httpd installation
  hosts: frontend
  vars:
    filename_to_deploy: index.html
    apache_port: 80
  tasks:

    - name: install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: run web tasks
      import_tasks: 'tasks/web_tasks.yml'

    - name: service start
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: open firewall port
      ansible.posix.firewalld:
        port: '{{ apache_port }}/tcp'
        immediate: true
        permanent: true
        state: enabled

    - name: deploy content
      ansible.builtin.copy:
        content: |
          {{ content_to_deploy }}
          Distribution is {{ ansible_facts.distribution }}
          Version is {{ ansible_facts.distribution_major_version }}
          IP address is {{ ansible_facts.default_ipv4.address }}
          IP address is {{ ansible_facts['default_ipv4']['address'] }}
          Distribution is {{ ansible_distribution }}
          Cached value is {{ var12345 | default('missing') }}
          probably wrong cached value is {{ ansible_facts.var12345 | default('missing') }}
        dest: /var/www/html/{{ filename_to_deploy }}

  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

