---
- name: vscode demo
  hosts: all
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest

    - name: start the service
      service:
        name: httpd
        state: started
        enabled: true
        