---
# tasks file for dbconfig
- name: install package
  ansible.builtin.dnf:
    name: "{{ dbconfig_package }}"
    state: present

- name: template out config
  ansible.builtin.template:
    src: mariadb-server.cnf.j2
    dest: /etc/my.cnf.d/mariadb-server.cnf

- name: ensure db directory exists
  ansible.builtin.file:
    path: "{{ dbconfig_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    setype: mysqld_db_t
    mode: 0755

- name: start service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: create user
  command: >
    mariadb -e 'CREATE USER {{ dbconfig_user }} IDENTIFIED BY "{{ dbconfig_password }}";'

- name: create database
  command: >
    mariadb -e 'CREATE DATABASE {{ dbconfig_database }};'
