---
- name: events about URLs
  hosts: all
  sources:
    - name: URL check
      ansible.eda.url_check:
        urls:
          - http://ec2-3-135-9-17.us-east-2.compute.amazonaws.com
        delay: 60
        
  rules:
    - name: debug
      condition: true
      action:
        debug:
          var: event
