---
- name: 'Add/update mariadb users'
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password | default(omit) }}'
  no_log: mariadb_debug == false
  when: mariadb_users|length and item.state is not defined or item.state != 'absent'
  with_items: '{{ mariadb_users }}'

# For all localhost users create 127.0.0.1 alias
- name: 'Add/update mariadb users'
  mysql_user:
    name: "{{ item.name }}"
    host: "127.0.0.1"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password | default(omit) }}'
  no_log: mariadb_debug == false
  when: mariadb_users_create_ip_alias and mariadb_users|length and (item.state is not defined or item.state != 'absent') and (item.host is not defined or item.host == 'localhost')
  with_items: '{{ mariadb_users }}'

- name: Remove mariadb users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    state: absent
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password | default(omit) }}'
  no_log: mariadb_debug == false
  when: mariadb_users|length and item.state is defined and item.state == 'absent'
  with_items: '{{ mariadb_users }}'

# For all localhost users create 127.0.0.1 alias
- name: Remove mariadb users
  mysql_user:
    name: "{{ item.name }}"
    host: "127.0.0.1"
    state: absent
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password | default(omit) }}'
  no_log: mariadb_debug == false
  when: mariadb_users|length and (item.state is defined and item.state == 'absent') and (item.host is not defined or item.host == 'localhost') and mariadb_users_create_ip_alias
  with_items: '{{ mariadb_users }}'
